source 'https://rubygems.org'
gem 'rails', '3.2.13'
gem 'pg'
#gem 'thin', :group => :production
gem 'therubyracer'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
  gem 'modernizr-rails'
end

gem 'coffee-rails'


group :development do
  gem 'html2haml', '>= 1.0.1'
  gem 'quiet_assets', '>= 1.0.1', :group => :development
  gem 'better_errors', '>= 0.6.0', :group => :development
  gem 'binding_of_caller', '>= 0.7.1', :platforms => [:mri_19, :rbx]
end

gem 'jquery-rails'
gem 'haml-rails', '>= 0.4'
gem 'rspec-rails', '>= 2.12.2', :group => [:development, :test]
gem 'database_cleaner', '>= 0.9.1', :group => :test
gem 'email_spec', '>= 1.4.0', :group => :test
#gem 'cucumber-rails', '>= 1.3.0', :group => :test, :require => false
gem 'launchy', '>= 2.2.0', :group => :test
gem 'capybara', '>= 2.0.2', :group => :test
gem 'factory_girl_rails', '>= 4.2.0', :group => [:development, :test]
gem 'bootstrap-sass', '>= 2.3.0.0'
gem 'hominid', '>= 3.0.5'
gem 'devise', '>= 2.2.3'
gem 'cancan', '>= 1.6.8'
gem 'rolify', '>= 3.2.0'
gem 'simple_form', '>= 2.0.4'
gem 'google_visualr', '>= 2.1.2'
gem 'jquery-datatables-rails', '>= 1.11.2'
gem 'figaro', '>= 0.5.3'


gem 'recaptcha', :require => 'recaptcha/rails'
gem 'aws-ses', '~> 0.4.4', :require => 'aws/ses'
gem 'date_validator'
gem 'faker'
gem 'aws-s3'
gem 'paperclip'
gem 'aws-sdk'
gem 'uuidtools'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'
gem 'omniauth', '>= 1.1.0'
gem 'omniauth-facebook'
gem 'ruby-units'
gem 'paypal-express'
gem 'rails-bootstrap-toggle-buttons', '~> 0.0.7'

gem 'forem', :git => "git://github.com/radar/forem.git"
gem 'forem-theme-twist', :git => "git://github.com/radar/forem-theme-twist"
gem 'airbrake'
